name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y autoconf automake make python3 m4
          ./init.sh
          ./configure.sh

      - name: Build
        run: |
          ./build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist